### ISSUE TITLE
Service phantomjs unexpectedly exited. Status code was: -6

### ISSUE THREAD

**Issue by isaaclw** [essandess/isp-data-pollution#15]
First:
- Installed mkvirtualenv

Ran:
```
cd ~/.virtualenv/ && virtualenv -p python3 isp-pollute
cd <git_repo>
workon isp-pollute
pip install numpy requests selenium Faker
sudo apt-get install phantomjs
```

This worked fine in ubuntu-12.04
But trying this in debian jessie (version 8) I get this crash:
```
$ python isp_data_pollution.py
Downloading the blacklist...
done.
Traceback (most recent call last):
  File "isp_data_pollution.py", line 483, in <module>
    ISPDataPollution(debug=True)
  File "isp_data_pollution.py", line 126, in __init__
    self.pollute_forever()
  File "isp_data_pollution.py", line 210, in pollute_forever
    self.open_session()
  File "isp_data_pollution.py", line 142, in open_session
    driver = webdriver.PhantomJS(desired_capabilities=dcap,service_args=['--ignore-ssl-errors=true','--ssl-protocol=any'])
  File "/home/isaac/.virtualenvs/isp-pollute/lib/python3.4/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/home/isaac/.virtualenvs/isp-pollute/lib/python3.4/site-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/home/isaac/.virtualenvs/isp-pollute/lib/python3.4/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: -6
```

I suspect it's a problem with phantomjs.
This is on a headless box.

```
$ apt-cache policy phantomjs
phantomjs:
  Installed: 2.1.1+dfsg-2~bpo8+1
  Candidate: 2.1.1+dfsg-2~bpo8+1
  Version table:
 *** 2.1.1+dfsg-2~bpo8+1 0
        100 http://ftp.us.debian.org/debian/ jessie-backports/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by essandess** [comment]
Yeah RPi! I was hoping someone would do this port.

I don't have an answer except to try some of the command line troubleshooting suggested here and let us know what's going on: https://github.com/essandess/isp-data-pollution/issues/6#issuecomment-292316026

**Comment by isaaclw** [comment]
> Yeah RPi! I was hoping someone would do this port.

What do you mean?

> try some commandline troubleshooting
```

(isp-pollute)isaac@tesla:~/.bin/src/isp-data-pollution$ which phantomjs
/usr/bin/phantomjs
(isp-pollute)isaac@tesla:~/.bin/src/isp-data-pollution$ which python3
/home/isaac/.virtualenvs/isp-pollute/bin/python3
(isp-pollute)isaac@tesla:~/.bin/src/isp-data-pollution$ which python
/home/isaac/.virtualenvs/isp-pollute/bin/python
(isp-pollute)isaac@tesla:~/.bin/src/isp-data-pollution$ ls -al /home/isaac/.virtualenvs/isp-pollute/bin/python
lrwxrwxrwx 1 isaac isaac 7 Apr  6 15:22 /home/isaac/.virtualenvs/isp-pollute/bin/python -> python3
(isp-pollute)isaac@tesla:~/.bin/src/isp-data-pollution$ python3 -c 'from selenium import webdriver; driver = webdriver.PhantomJS(); driver.get("https://github.com"); print(driver.title); driver.quit()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/isaac/.virtualenvs/isp-pollute/lib/python3.4/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/home/isaac/.virtualenvs/isp-pollute/lib/python3.4/site-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/home/isaac/.virtualenvs/isp-pollute/lib/python3.4/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: -6

```

I think there's hints in this stackoverflow answer, so I'm going to poke at that a bit and see if I get something...
http://stackoverflow.com/a/30103931

**Comment by isaaclw** [comment]
I wrote this patch:
```
diff --git a/isp_data_pollution.py b/isp_data_pollution.py
index f9b9f78..185fe32 100644
--- a/isp_data_pollution.py
+++ b/isp_data_pollution.py
@@ -22,6 +22,7 @@ __author__ = 'stsmith'

 import datetime as dt, numpy as np, numpy.random as npr, os, random, requests, signal, tarfile, time
 import urllib.request, urllib.robotparser as robotparser, urllib.parse as uprs
+from pyvirtualdisplay import Display
 from selenium import webdriver
 from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
 from io import BytesIO
@@ -30,6 +31,9 @@ from faker import Factory
 # nice this process on UNIX
 if hasattr(os,'nice'): os.nice(15)

+display = Display(visible=0, size=(1296,1018))
+display.start()
+
 gb_per_month = 50              # How many gigabytes to pollute per month
 max_links_cached = 100000      # Maximum number of links to cache for download
 max_links_per_page = 200       # Maximum number of links to add per page

```

Then I tried running again, and got this error:
```
Traceback (most recent call last):
  File "isp_data_pollution.py", line 487, in <module>
    ISPDataPollution(debug=True)
  File "isp_data_pollution.py", line 130, in __init__
    self.pollute_forever()
  File "isp_data_pollution.py", line 215, in pollute_forever
    self.seed_links()
  File "isp_data_pollution.py", line 250, in seed_links
    self.get_websearch(word)
  File "isp_data_pollution.py", line 371, in get_websearch
    if len(self.links) < self.max_links_cached: self.add_url_links(new_links)
  File "isp_data_pollution.py", line 427, in add_url_links
    if self.debug: print('Added {:d} links, {:d} total at url \'{}\'.'.format(k,len(self.links),self.session.current_url))
  File "/home/isaac/.virtualenvs/isp-pollute/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 515, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "/home/isaac/.virtualenvs/isp-pollute/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/home/isaac/.virtualenvs/isp-pollute/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 164, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Error - Unable to load Atom 'execute_script' from file ':/ghostdriver/./third_party/webdriver-atoms/execute_script.js'

```
So I found this page:
https://stackoverflow.com/questions/36770303/phantomjs-with-selenium-unable-to-load-atom-find-element
which I'm not convinced is realted... but basically using npm to install phantomjs-legacy on my debian headless system seems to have helped:
```
sudo apt-get install nodejs
sudo apt-get install nodejs-legacy
sudo apt-get install npm
sudo npm -g install phantomjs-prebuilt
```
https://stackoverflow.com/a/36843608

Now I'm just getting errors that look like this:


```
Added 0 links, 179 total at url 'https://www.google.com/search?q=terrific&gws_rd=ssl#spf=1'.
Seeding with search for 'fingerprint pea'...
Added 10 links, 188 total at url 'https://www.google.com/search?q=fingerprint%20pea&gws_rd=ssl#spf=1'.
Added 41 links, 228 total at url 'https://www.yahoo.com/news/sharon-osbourne-supports-mel-b-203407042.html'.
[Errno 9] Bad file descriptor
Seeding with search for 'fifth'...
Message: {"errorMessage":"Unable to find element with tag name 'a'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"116","Content-Type":"application/x-www-form-urlencoded","Host":"127.0.0.1:41396","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"value\": \"a\", \"id\": \":wdc:1491539291891\", \"using\": \"tag name\", \"sessionId\": \"9b7ab6d0-1b4a-11e7-93f9-3b600eb154d2\"}","postRaw":"{\"value\": \"a\", \"id\": \":wdc:1491539291891\", \"using\": \"tag name\", \"sessionId\": \"9b7ab6d0-1b4a-11e7-93f9-3b600eb154d2\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/9b7ab6d0-1b4a-11e7-93f9-3b600eb154d2/element/:wdc:1491539291891/element"}}
Screenshot: available via screen

Added 0 links, 228 total at url 'https://www.google.com/search?q=fifth&gws_rd=ssl#spf=1'.
Added 6 links, 233 total at url 'https://mobile.yahoo.com/sports'.
Seeding with search for 'exorcise'...
Message: {"errorMessage":"Unable to find element with tag name 'a'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"116","Content-Type":"application/x-www-form-urlencoded","Host":"127.0.0.1:44040","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"value\": \"a\", \"id\": \":wdc:1491539333683\", \"using\": \"tag name\", \"sessionId\": \"b464e350-1b4a-11e7-afe6-99c840365dcc\"}","postRaw":"{\"value\": \"a\", \"id\": \":wdc:1491539333683\", \"using\": \"tag name\", \"sessionId\": \"b464e350-1b4a-11e7-afe6-99c840365dcc\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/b464e350-1b4a-11e7-afe6-99c840365dcc/element/:wdc:1491539333683/element"}}
Screenshot: available via screen

Added 0 links, 233 total at url 'https://www.google.com/search?q=exorcise&gws_rd=ssl#spf=1'.
Added 47 links, 279 total at url 'http://sports.yahoo.com/'.
Seeding with search for 'artichoke'...
Added 11 links, 290 total at url 'http://www.google.com/search?q=artichoke'.
Added 201 links, 490 total at url 'https://play.google.com/store/apps/details?id=com.yahoo.mobile.client.android.im&referrer=af_tranid%3DTOESj0Q_FePq3XkNhDoazA%26pid%3DLandingPage%26c%3DIrisLaunch_Nov15%26af_sub1%3DInternal%26af_sub2%3DMYC_YMktg_Iris%26af_sub3%3DLandingPage_IrisMYC%26utm_source%3Dmobile.yahoo.com%26utm_medium%3Ddetailpagelink'.
Seeding with search for 'largemouth'...
Added 11 links, 501 total at url 'http://www.google.com/search?q=largemouth'.
Seeding with search for 'ivy audition'...
Added 10 links, 510 total at url 'http://www.google.com/search?q=ivy%20audition'.
Added 16 links, 525 total at url 'https://help.yahoo.com/kb/homepage/SLN14553.html?impressions=true'.
[Errno 9] Bad file descriptor

```

**Comment by isaaclw** [comment]
Seems to be working! (I left it running all night)
My only concern is this:

```
isaac@tesla:~$ ps -ef | grep phantomjs-prebuilt | wc -l
336
```

That's a lot of processes...

I noticed a whole lot of IO. Apparently it spawned processes till it used up all my memory and swap space?

I guess I need to spin up a virtual machine if this is how the program works.

**Comment by essandess** [comment]
Looks good except for the extra processes. I explicitly call the `quit` method after each GET to avoid this.

IIRC, someone mentioned on stackoverflow that their version of phantomjs wasn't responding to quit or close calls.

I suggest investigating in an ipython session and submitmitting an issue on the phantomjs repo if you can isolate the problem.

**Comment by isaaclw** [comment]
Can you try the pyvirtualdisplay changes at the top of:
https://github.com/essandess/isp-data-pollution/issues/15#issuecomment-292435948

To see if they also work in a non-headless scenario?

**Comment by isaaclw** [comment]
Also, I switched to debian's version of phantomjs since I see my other issue in https://github.com/essandess/isp-data-pollution/issues/15#issuecomment-292435948 was similar to https://github.com/essandess/isp-data-pollution/issues/13#issue-219728119 .

I pulled, switched to debian's, uninstalled npm's version, and I'll see if I get memory errors now.

**Comment by isaaclw** [comment]
> Can you try the pyvirtualdisplay changes at the top of: #15 (comment)
> To see if they also work in a non-headless scenario?

Actually, I tested, and they work, but I have a better idea instead of requiring another package for non-headless uses. Once you accept (or reject) my last pull request, I'll create a new one for these suggestions, and then we can close this thread.

**Comment by isaaclw** [comment]
Closed in https://github.com/essandess/isp-data-pollution/pull/20#issuecomment-293707114
