### ISSUE TITLE
0 links added

### ISSUE THREAD

**Issue by aeametal** [essandess/isp-data-pollution#19]
The script is running on Ub16.04. I don't get any error codes but it always get "0 links added" out of ~20 total. Is this normal behavior?

**Comment by essandess** [comment]
Nope, that's not working. The link count should grow steadily to ~100k links.

I'll add a debug flag option to the command line soon.

Watch for the next commit, run it, and report the error.

**Comment by essandess** [comment]
Please try again with the latest commit and debugging turned on:

```
python3 isp_data_pollution.py -g
```

**Comment by aeametal** [comment]
$ python3 isp_data_pollution.py -g
Downloading the blacklist… done.
Seeding with search for 'bongo Coronado'…
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
'http://www.google.com/search?q=bongo Coronado&safe=active': 0 links added, 20 total
Traceback (most recent call last):
  File "isp_data_pollution.py", line 599, in <module>
    ISPDataPollution()
  File "isp_data_pollution.py", line 167, in __init__
    self.pollute_forever()
  File "isp_data_pollution.py", line 295, in pollute_forever
    self.clear_session()
  File "isp_data_pollution.py", line 235, in clear_session
    self.session.execute_script('window.localStorage.clear();')
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 102, in check_response
    value = json.loads(value_json)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0

**Comment by essandess** [comment]
Run the test [SSCCE code](../../../essandess/isp-data-pollution/wiki/Python:-Short,-Self-Contained,-Correct-Example) and please report your versions of `phantomjs` and `ghostdriver`.

If this SSCCE code doesn't work, the script won't work.

**Comment by randrews01** [comment]
Oddly enough, sometimes I also see 0/900 links.  But then it refreshes and I see 20/ 940 links added.   I can also validate it's generating traffic as I'm recording everything coming from this host.  FWIW the SSCCE checks out as working for me.

**Comment by essandess** [comment]
Looks like it's working if some sites provide links, and the total grows to the maximum default of 100k.

Please be sure to pull the latest commit.
