### ISSUE TITLE
self.driver.capabilities["version"] : Error on debug

### ISSUE THREAD

**Issue by juleshenry** [essandess/isp-data-pollution#33]
When running with debug on, I get the following error. 
Traceback (most recent call last):
  File "isp_data_pollution.py", line 1132, in <module>
    ISPDataPollution()
  File "isp_data_pollution.py", line 243, in __init__
    self.check_chromedriver_version()
  File "isp_data_pollution.py", line 278, in check_chromedriver_version
    self.driver.capabilities["version"],
KeyError: 'version'

ChromeDriver version is 79.0.3945.36 on macOS. 
Is this key deprecated? seems like driver.capabilities['version'] is no longer supported.

**Comment by essandess** [comment]
@juleshenry Thanks there's several recent mods to Chrome I must address. I'll add this to the pile…

**Comment by yraen69** [comment]
Chrome 81.0.4044.113 same issue as above, which version of Chrome was the last one which worked?

**Comment by essandess** [comment]
> Chrome 81.0.4044.113 same issue as above, which version of Chrome was the last one which worked?

Not sure, but irrelevant: we should be in the latest.

I have code that fixes this—it’s a simple mid, but need the cycles to add it.

**Comment by yraen69** [comment]
Happy to ping you some BTC to get this fixed I know it's tough times... pop me an address

**Comment by marksilinio** [comment]
> Happy to ping you some BTC to get this fixed I know it's tough times... pop me an address

please follow the maintained fork:
https://github.com/marksilinio/isp-data-noize

**Comment by juleshenry** [comment]
Sure Mark,

I’ve been busy at work this week. I will get on this as soon as I can.
