### ISSUE TITLE
Error -  Too many levels of symbolic links

### ISSUE THREAD

**Issue by Braskaaa** [essandess/isp-data-pollution#7]
```
python3 isp_data_pollution.py
Downloading the blacklist...
done.
Traceback (most recent call last):
  File "isp_data_pollution.py", line 483, in <module>
    ISPDataPollution()
  File "isp_data_pollution.py", line 126, in __init__
    self.pollute_forever()
  File "isp_data_pollution.py", line 210, in pollute_forever
    self.open_session()
  File "isp_data_pollution.py", line 142, in open_session
    driver = webdriver.PhantomJS(desired_capabilities=dcap,service_args=['--ignore-ssl-errors=true','--ssl-protocol=any'])
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1541, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 40] Too many levels of symbolic links

```

**Comment by essandess** [comment]
It appears that there is a problem with your `phantomjs` install.

Here's the SSCCE for `phantomjs`. If this doesn't run, the script won't run.

```
which phantomjs
python3 -c 'from selenium import webdriver; driver = webdriver.PhantomJS(); driver.get("https://github.com"); print(driver.title); driver.quit()'
```
